export default {
  login: "odik91",
  id: 46963084,
  node_id: "MDQ6VXNlcjQ2OTYzMDg0",
  avatar_url: "https://avatars.githubusercontent.com/u/46963084?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/odik91",
  html_url: "https://github.com/odik91",
  followers_url: "https://api.github.com/users/odik91/followers",
  following_url: "https://api.github.com/users/odik91/following{/other_user}",
  gists_url: "https://api.github.com/users/odik91/gists{/gist_id}",
  starred_url: "https://api.github.com/users/odik91/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/odik91/subscriptions",
  organizations_url: "https://api.github.com/users/odik91/orgs",
  repos_url: "https://api.github.com/users/odik91/repos",
  events_url: "https://api.github.com/users/odik91/events{/privacy}",
  received_events_url: "https://api.github.com/users/odik91/received_events",
  type: "User",
  site_admin: false,
  name: "Ali Shoddiqien",
  company: null,
  blog: "",
  location: "Batam Island, Indonesia",
  email: null,
  hireable: null,
  bio: "I am a web developer with main programming language PHP with laravel framework and i also a cloud engineer with google cloud technology ",
  twitter_username: null,
  public_repos: 27,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2019-01-23T12:32:34Z",
  updated_at: "2024-08-25T11:39:43Z",
};
